function coeffs_a_opt = a_from_coeffs(t,in2)
%A_FROM_COEFFS
%    COEFFS_A_OPT = A_FROM_COEFFS(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Oct-2025 17:47:31

c2 = in2(:,2);
c3 = in2(:,3);
c4 = in2(:,4);
c5 = in2(:,5);
coeffs_a_opt = c2+c3.*t+(c4.*t.^2)./2.0+(c5.*t.^3)./6.0;
end
