function coeffs_a_opt = a_from_coeffs(t,in2)
%A_FROM_COEFFS
%    COEFFS_A_OPT = A_FROM_COEFFS(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Dec-2025 18:09:11

c3 = in2(:,3);
c4 = in2(:,4);
c5 = in2(:,5);
c6 = in2(:,6);
coeffs_a_opt = c3+c4.*t+(c5.*t.^2)./2.0+(c6.*t.^3)./6.0;
end
