function sf_j0_opt = final_opt_pos_j0(v0,a0,tf)
%FINAL_OPT_POS_J0
%    SF_J0_OPT = FINAL_OPT_POS_J0(V0,A0,TF)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    26-Nov-2025 11:24:13

sf_j0_opt = tf.*(v0.*4.0+a0.*tf).*(3.0./2.0e+1);
end
