function t_vf_sol = final_opt_time_pass(v0,a0,sf,vf)
%FINAL_OPT_TIME_PASS
%    T_VF_SOL = FINAL_OPT_TIME_PASS(V0,A0,SF,VF)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    13-Nov-2025 12:57:07

t_vf_sol = (sf.*3.0e+1)./(v0.*7.0+vf.*8.0-sqrt(a0.*sf.*6.0e+1+v0.*vf.*1.12e+2+v0.^2.*4.9e+1+vf.^2.*6.4e+1));
end
