function vf_j0_opt = final_opt_vel_j0(v0,a0,sf,tf)
%FINAL_OPT_VEL_J0
%    VF_J0_OPT = FINAL_OPT_VEL_J0(V0,A0,SF,TF)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Dec-2025 18:09:43

vf_j0_opt = ((sf.*-2.0e+1+tf.*v0.*1.2e+1+a0.*tf.^2.*3.0).*(-1.0./8.0))./tf;
end
