function tf_j0_opt_1 = final_opt_time_j0_1(v0,a0,sf)
%FINAL_OPT_TIME_J0_1
%    TF_J0_OPT_1 = FINAL_OPT_TIME_J0_1(V0,A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    26-Nov-2025 12:23:46

t2 = v0.*5.0;
tf_j0_opt_1 = ((t2+sqrt(5.0).*sqrt(a0.*sf.*8.0+t2.*v0)).*(-1.0./4.0))./a0;
end
