function sf_j0_opt = final_opt_time_stop_j0(v0,a0)
%FINAL_OPT_TIME_STOP_J0
%    SF_J0_OPT = FINAL_OPT_TIME_STOP_J0(V0,A0)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    26-Nov-2025 11:24:13

sf_j0_opt = (v0.*-2.0)./a0;
end
