function tf_j0_opt_all = final_opt_time_j0(v0,a0,sf)
%FINAL_OPT_TIME_J0
%    TF_J0_OPT_ALL = FINAL_OPT_TIME_J0(V0,A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Dec-2025 18:09:45

t2 = v0.*5.0;
t4 = 1.0./a0;
t5 = a0.*sf.*8.0;
t7 = sqrt(5.0);
t6 = t2.*v0;
t8 = t5+t6;
t9 = sqrt(t8);
t10 = t7.*t9;
tf_j0_opt_all = [t4.*(t2+t10).*(-1.0./4.0);t4.*(t2-t10).*(-1.0./4.0)];
end
