function coeffs_j_opt = j_from_coeffs(t,in2)
%J_FROM_COEFFS
%    COEFFS_J_OPT = J_FROM_COEFFS(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Nov-2025 19:40:37

c3 = in2(:,3);
c4 = in2(:,4);
c5 = in2(:,5);
coeffs_j_opt = c3+c4.*t+(c5.*t.^2)./2.0;
end
