function coeffs_s_opt = s_from_coeffs(t,in2)
%S_FROM_COEFFS
%    COEFFS_S_OPT = S_FROM_COEFFS(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Nov-2025 19:40:36

c1 = in2(:,1);
c2 = in2(:,2);
c3 = in2(:,3);
c4 = in2(:,4);
c5 = in2(:,5);
coeffs_s_opt = c1.*t+(c2.*t.^2)./2.0+(c3.*t.^3)./6.0+(c4.*t.^4)./2.4e+1+(c5.*t.^5)./1.2e+2;
end
