function T_star = time_min_vel_pass(v0,a0,sf,v_min)
%TIME_MIN_VEL_PASS
%    T_star = TIME_MIN_VEL_PASS(V0,A0,SF,V_MIN)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Oct-2025 19:40:07

T_star = (sqrt(1.5e+1).*sqrt(-a0.*sf))./a0;
end
