function coeffs_v_opt = v_from_coeffs(t,in2)
%V_FROM_COEFFS
%    COEFFS_V_OPT = V_FROM_COEFFS(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Dec-2025 18:09:11

c2 = in2(:,2);
c3 = in2(:,3);
c4 = in2(:,4);
c5 = in2(:,5);
c6 = in2(:,6);
coeffs_v_opt = c2+c3.*t+(c4.*t.^2)./2.0+(c5.*t.^3)./6.0+(c6.*t.^4)./2.4e+1;
end
