function coeffs_v_opt = v_from_coeffs(t,in2)
%V_FROM_COEFFS
%    COEFFS_V_OPT = V_FROM_COEFFS(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    13-Nov-2025 15:44:37

c1 = in2(:,1);
c2 = in2(:,2);
c3 = in2(:,3);
c4 = in2(:,4);
c5 = in2(:,5);
coeffs_v_opt = c1+c2.*t+(c3.*t.^2)./2.0+(c4.*t.^3)./6.0+(c5.*t.^4)./2.4e+1;
end
