/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * primitives.c
 *
 * Code generation for function 'primitives'
 *
 */

/* Include files */
#include "primitives.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Variable Definitions */
static boolean_T isInitialized_primitives = false;

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
static double rt_powd_snf(double u0, double u1)
{
  double d;
  double d1;
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    d = fabs(u0);
    d1 = fabs(u1);
    if (rtIsInf(u1)) {
      if (d == 1.0) {
        y = 1.0;
      } else if (d > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }
  return y;
}

void coef_list(double v0, double a0, double sf, double vf, double af, double T,
               double coef_list_var[6])
{
  double b_coef_list_var_tmp;
  double coef_list_var_tmp;
  double t2;
  double t3;
  double t4;
  double t4_tmp;
  if (!isInitialized_primitives) {
    primitives_initialize();
  }
  /* COEF_LIST */
  /*     COEF_LIST_VAR = COEF_LIST(V0,A0,SF,VF,AF,T) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.1.
   */
  /*     24-Oct-2025 17:47:31 */
  t2 = T * T;
  t3 = af * t2;
  t4_tmp = a0 * t2;
  t4 = t4_tmp * 3.0;
  coef_list_var[0] = 0.0;
  coef_list_var[1] = v0;
  coef_list_var[2] = a0;
  coef_list_var_tmp = T * v0;
  b_coef_list_var_tmp = T * vf;
  coef_list_var[3] = 1.0 / rt_powd_snf(T, 3.0) *
                     ((((sf * -20.0 + t4) - t3) + coef_list_var_tmp * 12.0) +
                      b_coef_list_var_tmp * 8.0) *
                     -3.0;
  coef_list_var[4] =
      1.0 / (t2 * t2) *
      ((((sf * -30.0 - t3 * 2.0) + t4) + coef_list_var_tmp * 16.0) +
       b_coef_list_var_tmp * 14.0) *
      12.0;
  coef_list_var[5] = 1.0 / rt_powd_snf(T, 5.0) *
                     ((((sf * -12.0 - t3) + coef_list_var_tmp * 6.0) +
                       b_coef_list_var_tmp * 6.0) +
                      t4_tmp) *
                     -60.0;
}

void primitives_initialize(void)
{
  rt_InitInfAndNaN();
  isInitialized_primitives = true;
}

void primitives_terminate(void)
{
  isInitialized_primitives = false;
}

void student_pass_primitive(double v0, double a0, double sf, double vf_min,
                            double vf_max, double T_min, double T_max,
                            double coeffsT2[6], double *v2, double *T2,
                            double coeffsT1[6], double *v1, double *T1)
{
  double u1;
  double u1_tmp;
  double v_star;
  int i;
  if (!isInitialized_primitives) {
    primitives_initialize();
  }
  /* #codegenvfmin */
  /*  */
  /*            Agent Logic */
  /*          Pass Primitive */
  /*               2025 */
  /*  */
  if (a0 >= 0.0) {
    /* FINAL_OPT_TIME_PASS */
    /*     T_VF_SOL = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.1. */
    /*     13-Nov-2025 12:57:07 */
    v_star = a0 * sf * 60.0;
    u1_tmp = v0 * v0 * 49.0;
    u1 = sf * 30.0 /
         ((v0 * 7.0 + vf_min * 8.0) -
          sqrt(((v_star + v0 * vf_min * 112.0) + u1_tmp) +
               vf_min * vf_min * 64.0));
    /* FINAL_OPT_TIME_PASS */
    /*     T_VF_SOL = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.1. */
    /*     13-Nov-2025 12:57:07 */
    v_star = sf * 30.0 /
             ((v0 * 7.0 + vf_max * 8.0) -
              sqrt(((v_star + v0 * vf_max * 112.0) + u1_tmp) +
                   vf_max * vf_max * 64.0));
  } else {
    v_star = 0.125 * (7.745966692414834 * sqrt(-a0 * sf) - 7.0 * v0);
    if ((v_star < vf_min) && (vf_min < vf_max)) {
      /* FINAL_OPT_TIME_PASS */
      /*     T_VF_SOL = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 24.1. */
      /*     13-Nov-2025 12:57:07 */
      v_star = a0 * sf * 60.0;
      u1_tmp = v0 * v0 * 49.0;
      u1 = sf * 30.0 /
           ((v0 * 7.0 + vf_min * 8.0) -
            sqrt(((v_star + v0 * vf_min * 112.0) + u1_tmp) +
                 vf_min * vf_min * 64.0));
      /* FINAL_OPT_TIME_PASS */
      /*     T_VF_SOL = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 24.1. */
      /*     13-Nov-2025 12:57:07 */
      v_star = sf * 30.0 /
               ((v0 * 7.0 + vf_max * 8.0) -
                sqrt(((v_star + v0 * vf_max * 112.0) + u1_tmp) +
                     vf_max * vf_max * 64.0));
    } else if ((vf_min < v_star) && (v_star < vf_max)) {
      u1 = sqrt(15.0 * sf / -a0);
      /* FINAL_OPT_TIME_PASS */
      /*     T_VF_SOL = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 24.1. */
      /*     13-Nov-2025 12:57:07 */
      v_star = sf * 30.0 /
               ((v0 * 7.0 + vf_max * 8.0) -
                sqrt(((a0 * sf * 60.0 + v0 * vf_max * 112.0) + v0 * v0 * 49.0) +
                     vf_max * vf_max * 64.0));
    } else {
      u1 = 0.0;
      v_star = 0.0;
    }
  }
  /*     [T1, T2] = [T_min, T_max] ∩ [Tvmax, Tvmin] */
  if ((T_min >= v_star) || rtIsNaN(v_star)) {
    *T1 = T_min;
  } else {
    *T1 = v_star;
  }
  if ((T_max <= u1) || rtIsNaN(u1)) {
    *T2 = T_max;
  } else {
    *T2 = u1;
  }
  if ((*T1 > 0.0) && (*T1 <= *T2)) {
    /* FINAL_OPT_VEL_PASS */
    /*     VF_SOL = FINAL_OPT_VEL_PASS(V0,A0,SF,TF) */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.1. */
    /*     13-Nov-2025 12:57:01 */
    *v1 = ((sf * -15.0 + *T2 * v0 * 7.0) + a0 * (*T2 * *T2)) * -0.125 / *T2;
    /* FINAL_OPT_VEL_PASS */
    /*     VF_SOL = FINAL_OPT_VEL_PASS(V0,A0,SF,TF) */
    /*     This function was generated by the Symbolic Math Toolbox
     * version 24.1. */
    /*     13-Nov-2025 12:57:01 */
    *v2 = ((sf * -15.0 + *T1 * v0 * 7.0) + a0 * (*T1 * *T1)) * -0.125 / *T1;
    coef_list(v0, a0, sf, *v2, 0.0, *T1, coeffsT1);
    coef_list(v0, a0, sf, *v1, 0.0, *T2, coeffsT2);
  } else {
    *v1 = 0.0;
    *v2 = 0.0;
    for (i = 0; i < 6; i++) {
      coeffsT1[i] = 0.0;
      coeffsT2[i] = 0.0;
    }
  }
}

void student_stop_primitive(double v0, double a0, double sf, double coefs[6],
                            double *maxsf, double *tf)
{
  double d;
  int i;
  if (!isInitialized_primitives) {
    primitives_initialize();
  }
  /*  */
  /*           Agent Logic */
  /*          Stop Primitive */
  /*               2025 */
  /*  */
  /*  Function */
  /*  This function must to be converted in c code using coder add-on. */
  /*  Copy from this path C:\Program Files\MATLAB\R2024a\extern\include */
  /*  Define the folder to get matlabfunction */
  /*  before typing "coder", execute these lines to add the folder to the */
  /*  project path */
  /*  nameExportFolder = 'functions_exported'; */
  /*  currentFolder = pwd; */
  /*  exportFolder = fullfile(currentFolder, nameExportFolder);
   * %...\matlab\def_functions */
  /*  if ~exist(exportFolder, 'dir') */
  /*      mkdir(exportFolder); */
  /*  end */
  /*  addpath(exportFolder); */
  /*  Stopping Primitive */
  if ((v0 <= 0.0) || (sf == 0.0)) {
    /*  --- Early exits --- */
    *maxsf = 0.0;
    *tf = 0.0;
    for (i = 0; i < 6; i++) {
      coefs[i] = 0.0;
    }
  } else {
    d = 4.0 * (v0 * v0);
    if (d + 5.0 * a0 * sf < 0.0) {
      /*  --- Unfeasible case --- */
      *maxsf = -d / (5.0 * a0);
      *tf = 10.0 * *maxsf / (2.0 * v0);
    } else {
      /*  --- Feasible case --- */
      *maxsf = sf;
      /* FINAL_OPT_TIME_STOP */
      /*     TF_SOL = FINAL_OPT_TIME_STOP(V0,A0,SF) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 24.1. */
      /*     24-Oct-2025 19:57:27 */
      *tf = sf * 10.0 / (v0 * 2.0 + sqrt(a0 * sf * 5.0 + d));
    }
    coef_list(v0, a0, *maxsf, 0.0, 0.0, *tf, coefs);
  }
}

/* End of code generation (primitives.c) */
