function vf_sol = final_opt_vel_pass(v0,a0,sf,tf)
%FINAL_OPT_VEL_PASS
%    VF_SOL = FINAL_OPT_VEL_PASS(V0,A0,SF,TF)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Dec-2025 18:09:35

vf_sol = ((sf.*-1.5e+1+tf.*v0.*7.0+a0.*tf.^2).*(-1.0./8.0))./tf;
end
