function Tsf_j0_opt = final_opt_time_stop_j0(v0,a0)
%FINAL_OPT_TIME_STOP_J0
%    Tsf_j0_opt = FINAL_OPT_TIME_STOP_J0(V0,A0)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Dec-2025 18:09:59

Tsf_j0_opt = (v0.*-2.0)./a0;
end
