function tf_sol = final_opt_time_stop(v0,a0,sf)
%FINAL_OPT_TIME_STOP
%    TF_SOL = FINAL_OPT_TIME_STOP(V0,A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Dec-2025 18:09:51

tf_sol = (sf.*1.0e+1)./(v0.*2.0+sqrt(a0.*sf.*5.0+v0.^2.*4.0));
end
