function v_star = min_vel(v0,a0,sf)
%MIN_VEL
%    V_STAR = MIN_VEL(V0,A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Dec-2025 18:09:36

t2 = a0.*sf;
t3 = -t2;
v_star = (1.0./sqrt(t3).*(sqrt(1.5e+1).*t2.*2.0-sqrt(t3).*v0.*7.0))./8.0;
end
