function T_star = time_min_vel_pass(a0,sf)
%TIME_MIN_VEL_PASS
%    T_star = TIME_MIN_VEL_PASS(A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Dec-2025 18:09:36

T_star = (sqrt(1.5e+1).*sqrt(-a0.*sf))./a0;
end
